### ISSUE TITLE
Create a template for new PRs and issues

### ISSUE THREAD

**Issue by cliffpyles** [BioMediaLab/whiteboard#3]
To help create consistency and effective communication around the work being done on the project, we need to introduce templates that will automatically generate boilerplate PRs and issues for contributors.

This will help the person reviewing the PR understand what they are reviewing. It will also help with the documentation of the context for future contributors.

**Comment by cliffpyles** [comment]
I think the templates here are great to try for starters. https://github.com/angular/angular/tree/master/.github

@andyk91 @megsachdev What do you think?

**Comment by megsachdev** [comment]
@cliffpyles this sounds good to me. We will have a consistency throughout the project then..

**Comment by cliffpyles** [comment]
Awesome. Thanks @megsachdev ! I'm a big fan of never merging your own work. Would you mind merging PR #4 when you have a minute?
