### ISSUE TITLE
Create a container for listing quiz templates

### ISSUE THREAD

**Issue by cliffpyles** [BioMediaLab/whiteboard#31]
## Overview

The application has a top-level entity called a QuizTemplate. We need a container that implements the loading and display of this entity type.

## Acceptance Criteria

The container should contain the following presentational components:

- Card
- Page
- SkeletonPage
- Title
- ResourceList

The list item should display the following properties from the typedefs:

- title
- description

The following queries can be used from the generated graphql operations:

- listQuizTemplates

The route should be `/quiz-templates`

*The CourseList container can be used as a reference. A preview can be viewed here: https://develop.d2gal5mfya2zo2.amplifyapp.com/courses

** The type definitions can be viewed in the project at this location: amplify/backend/api/whiteboard/schema.graphql

**Comment by megsachdev** [comment]
Looks great!!
